name = "nFiniteGroups"
uuid = "dc2ae139-e50a-4fc2-8438-b6cf65b9500c"
authors = ["julia-KAERI <julia.kaeri@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
LinearAlgebra = "1.11.0"
OrderedCollections = "1.8.0"
Printf = "1.11.0"
